language: node_js

cache: yarn
services: docker

branches:
   only:
    - master

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

env:
  global:
    # DOCKER_PASSWORD
    - secure: dIZomGeV5y/VYJnOdkaWK6dVZnq4p2I+5Lwo1ib4Z1hSoRNhEf8eXOLpFOvD3T6G1t+zi83Ae0mzwvkVWM0EIAFCAsHuTXz+yyKX/JOJiygCSta6dlDg3Vsmk5ucT6h9HYRJfrvfJts1A4uADEV/p+4iVdAXNrIC7UznuutFrfoLrj2MzvYo1dukAV2UxRD2o4qQRfqfHLL2ECIhk2jsMy3JGva/MU8G0+hKGWauhawLDqvldWJfKcTmZOGy9ZOxI+ihvwW1ENIA4FCf/Fr4E2OnEQh2irRmiJJ6eL/kKrnjWk/buEFo1fFMgAYYr4hEoKPmpzu6RmugEHow49m/Vm1uuQD4DjkLNbykslyVF2XQur/aJzUfdbtgQjNoVE2eqmqXotgeksJHIGkrjHt0ZVR98AmLRAE2zVyMlg6gZxksWiTq0yMHqKKijlqHUkOEU+pNm/wvu3Tq1/rijNtJzWczXFRlpb8vkay6hvnPC4RrPUprkScr6Qybv9VoaCUIWaK3iSf2CfePYRd9js0drXZDq5jnX2qGgMJ3nd0d1f91rUpwAlMbEfI23RsD2YmNvOENPWMYq1DqGW92vJPj6STZwvB0SGQo59Ogl6U93MneJ1tivVc8Yvl3w4/v6Myb/LowP2Y1IPQTW/nSUphpLXb0hpsbRts1J8eqxPJTadU=
    # NAMESPACE
    - secure: o2Eqah1I97sA2AmL9+u3mehxE7Szqmi4SSLnKSmmytg/rnT5AiaceEk/sqJX/moYhS7Nlpc0kw2dHxH9EI3X7KraiTwQbuzpFanDDOxz1nBtKPd43ODpX7IqnBinDoSqxA9P0V3KSu9GIxEavPMjW/C7zgaG+Vn7i0/jQTFVcfbZBGhP6aGdDoIYsqeR8PcO7P9ZIpxWEEuT1odSc19WsMbHT2b3O1oE709MWa0UIRiZT8YXgeYHBHRwk9PStgad5ZL7hEbf9B/EZPAFwl8BY9OuioFsUjCP/HvwmyMCSwpr/mloWyZxGIsHbpHwVT7cgO3+w5vXLVOP9L3cLJWz6Q6R6+U1azdP1TU6ZBTTPuE08IEwoV/BuvXuxlaiFzIYTWv2Wkw+dqgPpNIcpKHzaCJ/LA5TPhfSTiZgajTGpQN9kbTIUqsWihIkCldFP/XO0OC+ZA83w0r2dhtmb91TW0y8icYntJbVMg7hyenW5jlTcFIfkjHa7We4RwULsXpVzGQ8JYe4apirG9HxwWO18XzwNiF11M8L+6hmgi/1shGybIn0TsrwAyjqQ7hQaKHn3PoCgIsSvt9eMhOMm8Hgn7K+QelX/bj9GCTzblrCJlCBsPWko2lQbbaUlKL3e0qU9+OaGYE6YDV0XmZxU+MlgHeZ+2hJbFzCXtnVCb7p64Y=
    # GITHUB_TOKEN
    - secure: qG11tLV4qUw2/40sDOYMgoPUnhqcJiEuAHKES6PgCaCxpCLSowpBnoXmnBO18MZoPRsfz3oMuj2bQizXjJnx2mjtX1achy2AvDa2OXsXHPD1F+fRnbsj+KUeHPsg6eo5tdri/YOV52X1JW1l4kyklrS+2qSAzPBjzslHtXB2dTtYRcwxbdaoaAQjzblJNxxbAGHV88ZOy4wzknvIdGJ1UvWe9gE7XW5mLqsoU5WBZPn4TVMuOcg0gtZR4T1SKa/Xl0c2+JikBLT4s8sQSQN+5aW0BifyK4X0N9rTegGco06ZpdDPp5hpqbrh/dJKa2nE03MXL66H3kbMiORPaCmGXPkxWUM0YwyB1f6WCaKuhWblYd3UJp6u/mPHBJesYF3vUElsycW/mY05BHxE+CvtTeHV+WwB2PDsBYL/mYGQLQxOxbf1ch+I47mHdqzl/ahjzmI0N8XTLlrjlSbXcRk6d2oiYecW6OLiFP5PrFRwRQga4XaJeabM65wnxbh5d922Ba5BMxRqxgpx6vOrLQ8ocIQEkh6i7FeqbX7Ez8IOWJRYY98CCt4sWmMgou0KVHoFR+d2hkp1yfQsBVHCZZlzwDpb+pHsnT0jXXGw8xTRgHlP0HoXfC7Hbm+qucJD6796H1HPIE/FfbSqmMU/VBjug4CZ7176QnuXsr+StpexOzY=

jobs:
  include:
    - stage: build staging
      node_js: "7"
      env:
        - ENV=staging
        # KEY
        - secure: ZZVx3o6xDngkon6tOxz28VSjY037+deExhRyMAGrlnFpNXIa1aRxVu8HD4X9HoQPNiMp2XBJod0y0WCdLFye2KBu5QTn3aycWnt0Ucp2MbP1cX1lKEMXZZ2BnbazLrGjlratYluPvd2QRZsFTDLfsHQe85bYysTQoHr6gRpt7h1sy9eKe2QKBtNA8Mp6nBAPSK98pD66jU/SYENYS971rvwFH9C+tbB0rUAY5Dfi99uiMrAKnrh05v3dHlCgRhZn3Bb4zOgPlvOgrK7JalSRRfFSogCaCe+sHv6oUZac4s1kBuLvNikR09wW/7b7ZpJzEC9hq5SEWEPawUTOUfyO0dmO+N1ogu/f0d+X2elhJ4Fw1GWYPXEdep0RWHpKVb8ZrG+cFGvPM9tHFJt0QIG/j+MYX2dv08l1pkIkhGD8Bku0qhoHiJaUWIYkI2C/4ZEXZEGtOngLMEFysos4grFq/yTPftoVm63PTT3MTcBRgZK2Y+4Ng7m1eAO/oU1qMjhf44nJS6sWU9dti4q7eajj+NUvvN26XYpJTlCH6Z05K+PfEL3wkCjXe7HhaOw7q1Pmd3WAPEy+8gmJfVI1082zC/t4IDX2JgazxgmByKVqbUCVc+ornEyy70khmid3sKXOYe+1AILu0tOwumdN3VTm5HueOvvBCQ7nue2HnhLd5xc=
      script:
        - npm test
        - npm run build:${ENV}
      deploy:
        provider: script
        script: scripts/publish_sdk.sh ${ENV}
        skip_cleanup: true
        on:
          branch: master
    - stage: build sandbox
      node_js: "7"
      env:
        - ENV=sandbox
        - FILENAME_SUFFIX=_latest
        # KEY
        - secure: Pr5wRAwt9B+jg93oOsCwAe4zayyGbUkpt37epL6Zb+pCSnAiewVmjw7A6DN7qlPk7SDeALXefTapWrGPniztVjnDRX16x7ISWv8snzg3oonFTKh90QQQ+rkacBgHoZHUZAKcnewVGvyavMXwZAFRzB34RYkIOBGDB2Q7w7v9evYJHvAxPnEFyvRid3+WEML9fXR8bX6UT7uRIj9y21p+VhdSlesfN7IgRGWC5L2QwV/OZePoURPcyavK7F60PSg6Izx0V7t1i5Qe1h88qjkaJ+2VXywrM4FLKPuTJyoLMe7XxHQfdc6KibiZ1kcbhKN+6/JLyqMcxSjjfs1bRqA0t8j0+Zgj3EqzFTZwUnPzcJ7UKpUzAQg/AoDr4rZ0zqet+nZ8o2jg/MGjkSs4DOqe1NUsv1B66T488Oy1LyjL98bXrvcXVBVQuXgcSFiu2En9SRvfDKybygrT8Vtz7sdcT20tArSV4mN8r7Er8hFc3c0mHcwjIqYUrO/vJqyMh/RC2iddHj2vMLWpQBfVDZulaTgKrN66qyEzkNMKHX8hvag66yd4w2nLZpGNLOerblpGz9kgmqlGUqsrxl9FesJbCIJK3fPlGnUJvMVeybnSasZqXbAev1jIJUUjaziDN7jlf9VsV/B3kaF0AciV2LM4IYe1xC7vZKyK/xhSuuqCAfM=
      script:
        - npm test
        - npm run build:${ENV}
      deploy:
        provider: script
        script: scripts/publish_sdk.sh ${ENV}
        skip_cleanup: true
        on:
          branch: master
    - stage: build production
      node_js: "7"
      env:
      - ENV=sandbox # change to PRODUCTION as soon as endpoint is available
      script:
        - npm test
        - npm run build:${ENV}
        - sha256sum dest/healthcloud_sdk.js > dest/healthcloud_sdk.js.sha256
      deploy:
        provider: releases
        # script: scripts/publish_sdk.sh ${ENV} # add as soon as target script works with prod CDN
        api_key:
          secure: WOYmo7ez16Xv/Gzm/k1BL8gtJXSys2D+l87g9yc9ShV1JQhcernnpoLQunjDof4ZC/qzPo36hpJ50o7Dt4TYoAJiASWBoBEGFj10113jGGOAMol57sUiPxl/NJVqRWdK+JNJUARCixaVveEYEltyKRkFurGGRKw7F8PjtJwzOZzUMa4L9wmi2HRMp8pDPiHqL9NXvmLx/N5LmLCgFMgoZUV+22ZSA7EDzU6UvTB+M1HynxKJqvzJeyFi0k9mli5B/Z2e77zYbJuVnps1c4X+k0ldDh/tNeZeGr84/cC6gkpzLb4etWCF42Kix3Wyxcb6+G4T4JBDJZYNlMpOMAbfOkpSB1Dq9KloE+ODmXZkMgrwDRP5frqGDzbmj41BXx9XIKbYLC/j6eC4Dqv0zpjtIvZB6uyVEsXsKMDybIJEzDcSvbBQmwlIBXysdQhSiOj8lSYSL9AA0x/FKdthqJyElvSBuFgkbLN7afDuit2TUgZw/zfHOYIJYeJmvvAkXHhytmxH3CRxqHxlohfWEDmpQ62/AoJ5Ad4/LMD0vK/agNxwfryvO4Y72TqMhdUnCyPx4POr1+KRVniYTD6E93gX3sZgu0nKmZcxmMYEWSCVTdP13ub7nI9yc/JedrWjKx7ITQb4308mKNqZUV9eoGReUFhFz4/thMvW7a5HNWqIht0=
        file:
          - dest/healthcloud_sdk.js
          - dest/healthcloud_sdk.js.map
          - dest/healthcloud_sdk.js.sha256
        skip_cleanup: true
        on:
          tags: true
          branch: master
notifications:
  slack:
    - secure: U12cDibXLhyPxkY7dOw9/qMSQ0O4gzgELf18RuQLFVWSM9A61ACzUrYt7+JT9tn/+kNwyxOFsxkU35pWC+v9vl0u6OsOIceyOiMikwIbVVvhQrG51pE9kVW6tP/xhakUSrs0cHJqBN8OcviQbWp2nf+Z9YPJFrNOIgNipKNdiLBOXh4calxP4cNAOd5IIzB5Ouk6B5bRHcyOb2K0RNjUHpsDQbIq+/VPCNbpCS9G7Taf5CUjdFZFdViHBiQsZvmywpm+fO1fCdzi/b4Rwo+fiHVz7rumGF0UkcBMnw03QB6+hxU0TnmO8o1wJ4Ej0UyUtnszwOAsnThi9lL17YBI7YhcTZOlhF+DXmL4mD6hklhnhioL4vQvo7KZ2LWYDaD0SG5oHw4kGfy3mm28oVpaF9Dyh27oFmNeUFGwqcmqSSxK4txkuApQJWlgQ5pI4K8U66uICKchgNwkU3V18CLB6S52uhOT3Tt2ngE1112ymUwEWqy7KnPorKmetfRSD9oKILTKaCkkP93pF80YLKaZtQ5i3G9jQ0juEfYeXgRouY4r6f03Tw+1IK38yS3iMPt+pC24EQGc6ukq+gF6zd6+BUoIP4ITaCtUA49J6+NOXRfGUuw9V0tQWY/P6cod9SMK7LkhTtMA3iiMBoJq1RXdQTv1IaN20+kNbxbgAQkOTsM=
